# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version: 22
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - run: npm test

  check:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version: 22
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - run: npm run check

  lint-package:
    name: Lint package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version: 22
      - run: npm ci --ignore-scripts --no-audit --no-fund
      - name: Build package
        run: npm run build
      - name: Lint package
        run: npx publint

  npm-audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version: 22
      - name: npm audit
        run: npm audit --audit-level=high
